#!/usr/bin/osascript -l JavaScript
// Copyright (c) 2024 Erik Ben Heckman, shared under the GPL-3.0 license
// <https://github.com/heckman/photos-server>
//
//
//  captures links to media items selected in Apple Photos
//
//
//

ObjC.import("AppKit");

const app = Application.currentApplication();
app.includeStandardAdditions = true;

function run(args) {
	// this is a little awkward, but it's working
	env.init({ bundlePath: args[1] });
	launchAgent.init(resource("serverctl"));

	config.init(args[0], {
		origin: "http://photos.local",
		browser: "Safari",
		port: "6330",
	});
	primeModal();
}
const env = (() => {
	const environment = {};
	return {
		init: (values) => {
			Object.keys(values).forEach(
				(key) => (environment[key] = values[key]),
			);
		},
		get: (key) => environment[key],
		set: (key, value) => (environment[key] = value),
	};
})();
function resource(name) {
	return env.get("bundlePath") + "/Contents/Resources/" + name;
}

const launchAgent = (() => {
	// Get the URL to the main executable in the MacOS folder
	// const serverctl =
	// 	$.NSBundle.mainBundle.executableURL.URLByDeletingLastPathComponent.URLByAppendingPathComponent(
	// 		"serverctl",
	// 	).path.js;
	return {
		init: (script) => {
			serverctl = script;
		},
		status: () => app.doShellScript(`'${serverctl}' status`),
		start: (port) =>
			app.doShellScript(`'${serverctl}' start ${port}`),
		stop: () => app.doShellScript(`'${serverctl}' stop`),
		port: () => app.doShellScript(`'${serverctl}' port`),
		isRunning: () => {
			try {
				app.doShellScript(`'${serverctl}' test`);
				return true;
			} catch {
				return false;
			}
		},
	};
})();

function pause(message) {
	return infobox(message, 1.5);
}
function infobox(message, timeout = 0) {
	app.displayDialog(message, {
		withTitle: "Photos Server",
		withIcon: Path(resource("AppIcon.icns")),
		givingUpAfter: timeout, // Dismisses after 1 second
		buttons: ["Dismiss"],
		defaultButton: "Dismiss",
	});
}

function primeModal() {
	const browser = config.get("browser");
	const origin = config.get("origin");
	const port = launchAgent.port();
	const redirections = app
		.doShellScript(
			`${resource("redirections")} ${origin.replace(/^.*\/\//, "")}||:`,
		)
		.trim();
	const choices = {
		restart: { label: "Change the port", action: portModal },
		remove: {
			label: "Disable the server",
			action: () => {
				launchAgent.stop();
				pause("Disabling server");
				return true;
			},
		},
		start: { label: "Enable the server", action: portModal },
		origin: {
			label: "Set URL prefix that will open in Photos",
			action: originModal,
		},
		browser: {
			label: "Set browser for everything else",
			action: browserModal,
		},
		redirections: {
			label: "Display configured redirections",
			action: () => redirectionsModal(redirections),
		},
		homepage: {
			label: "Visit Photos Server homepage and close",
			action: () => {
				pause("Opening homepage...");
				app.doShellScript(
					`open -a "${browser}" https://github.com/heckman/photos-server`,
				);
				return false;
			},
		},
	};

	let list = launchAgent.isRunning()
		? [choices.restart.label, choices.remove.label]
		: [choices.start.label];
	let status = `${launchAgent.status()}

Links beginning with "${origin}"
will open in Photos.

Everything else will open in ${browser}.`;

	list = [...list, choices.origin.label, choices.browser.label];

	if (redirections) list = [...list, choices.redirections.label];

	list = [...list, choices.homepage.label];

	const choice = app.chooseFromList(list, {
		withTitle: "Photos Server Control",
		withPrompt: status,
		defaultItems: [],
		okButtonName: "Select",
		cancelButtonName: "Done",
		multipleSelectionsAllowed: false,
		emptySelectionAllowed: false,
	});
	if (choice === false) return;
	if (
		Object.values(choices)
			.find((c) => c.label === choice[0])
			.action()
	)
		primeModal();
}

function redirectionsModal(redirections) {
	infobox(
		redirections
			? "These redirections are configured, but not necessarily enabled.\n\n" +
					redirections
			: "No redirections configured",
	);
	return true;
}
function originModal() {
	try {
		const origin = app.displayDialog(
			"URLs begining with this prefix will be opened in Photos.\n(http:// will pre prepended if the scheme is not entered here.)",
			{
				defaultAnswer: config.get("origin"),
				hiddenAnswer: false,
				buttons: ["Cancel", "OK"],
				defaultButton: "OK",
				cancelButton: "Cancel",
				withTitle: "Photos Server: Set Origin",
			},
		);
		config.set(
			"origin",
			"http://" + origin.textReturned.replace(/^.*\//, ""),
		);
	} catch {
		// ignore error
	}
	return true;
}

function browserList() {
	const appURLs =
		$.NSWorkspace.sharedWorkspace.URLsForApplicationsToOpenURL(
			$.NSURL.URLWithString($("https://apple.com")),
		);
	return appURLs.js
		.map((url) => {
			const name =
				$.NSFileManager.defaultManager.displayNameAtPath(
					url.path,
				);
			// Force a native JS string primitive
			return String(ObjC.unwrap(name));
		})
		.filter((name) => name !== "Photos Server");
}
function browserModal() {
	const browser = app.chooseFromList(browserList(), {
		withTitle: "Photos Server Preferences",
		withPrompt: "Select Default Browser",
		defaultItems: [config.get("browser")],
		okButtonName: "Select",
		cancelButtonName: "Cancel",
		multipleSelectionsAllowed: false,
		emptySelectionAllowed: false,
	});
	if (browser !== false) {
		config.set("browser", String(browser[0]));
	}
	return true;
}

function portModal(errorMessage = "Select the port") {
	try {
		const port = app.displayDialog(errorMessage, {
			defaultAnswer: config.get("port"),
			hiddenAnswer: false,
			buttons: ["Cancel", "OK"],
			defaultButton: "OK",
			cancelButton: "Cancel",
			withTitle: launchAgent.isRunning()
				? "Photos Server: Change Listening Port"
				: "Photos Server: Enable Server",
		});
		if (port.buttonReturned === "OK") {
			try {
				launchAgent.start(port.textReturned);
				pause("Enabling server");
			} catch (e) {
				portModal(e.message);
			}
		}
	} catch {
		//
	}
	return true;
}

const config = (() => {
	let d;
	// ensure all defaults have persistent values
	return {
		init: (bid, defaults) => {
			d = $.NSUserDefaults.alloc.initWithSuiteName(bid);
			Object.keys(defaults).forEach((key) => {
				if (d.objectForKey(key).isNil())
					d.setObjectForKey($(defaults[key]), key);
			});
		},
		get: (key) => d.objectForKey(key).js,
		set: (key, value) => d.setObjectForKey($(value), key),
	};
})();
