#!/usr/bin/osascript -l JavaScript
// Copyright (c) 2024 Erik Ben Heckman, shared under the GPL-3.0 license
// <https://github.com/heckman/photos-server>
//
//
//  captures links to media items selected in Apple Photos
//
//
//

const bid = "ca.heckman.PhotosServer";
const app = Application.currentApplication();
app.includeStandardAdditions = true;

const launchAgent = (() => {
	// Get the URL to the main executable in the MacOS folder
	// const serverctl =
	// 	$.NSBundle.mainBundle.executableURL.URLByDeletingLastPathComponent.URLByAppendingPathComponent(
	// 		"serverctl",
	// 	).path.js;
	const serverctl =
		"/Applications/Photos Server.app/Contents/Resources/serverctl";
	return {
		status: () => app.doShellScript(`'${serverctl}' status`),
		start: (port) =>
			app.doShellScript(`'${serverctl}' start ${port}`),
		stop: () => app.doShellScript(`'${serverctl}' stop`),
		port: () => app.doShellScript(`'${serverctl}' port`),
		isRunning: () => {
			try {
				app.doShellScript(`'${serverctl}' test`);
				return true;
			} catch {
				return false;
			}
		},
	};
})();

function pause() {
	delay(0.2);
}

function primeModal() {
	const browser = config.get("browser");
	const origin = config.get("origin");
	const port = launchAgent.port();
	const redirections = app
		.doShellScript(
			`/Applications/Photos\\ Server.app/Contents/MacOS/redirections ${origin.replace(/^.*\/\//, "")}||:`,
		)
		.trim();
	const choices = {
		restart: { label: "Restart the server", action: portModal },
		remove: {
			label: "Remove the server",
			action: () => {
				launchAgent.stop();
				pause("Removing server");
				return true;
			},
		},
		start: { label: "Start the server", action: portModal },
		origin: {
			label: "Set URL prefix that will open in Photos",
			action: originModal,
		},
		browser: {
			label: "Set browser for everything else",
			action: browserModal,
		},
		redirections: {
			label: "Display configured redirections",
			action: () => redirectionsModal(redirections),
		},
		homepage: {
			label: "Visit Photos Server homepage and close",
			action: () => {
				app.displayAlert("Opening homepage...", {
					givingUpAfter: 1,
				});
				app.doShellScript(
					`open -a "${browser}" https://github.com/heckman/photos-server`,
				);
				return false;
			},
		},
	};

	let list = launchAgent.isRunning()
		? [choices.restart.label, choices.remove.label]
		: [choices.start.label];
	let status = `${launchAgent.status()}

Links beginning with "${origin}"
will open in Photos.

Everything else will open in ${browser}.`;

	list = [...list, choices.origin.label, choices.browser.label];

	if (redirections) list = [...list, choices.redirections.label];

	list = [...list, choices.homepage.label];

	const choice = app.chooseFromList(list, {
		withTitle: "Photos Server Control",
		withPrompt: status,
		defaultItems: [],
		okButtonName: "Select",
		cancelButtonName: "Done",
		multipleSelectionsAllowed: false,
		emptySelectionAllowed: false,
	});
	if (choice === false) return;
	if (
		Object.values(choices)
			.find((c) => c.label === choice[0])
			.action()
	)
		primeModal();
}

function redirectionsModal(redirections) {
	app.displayAlert(
		redirections
			? "Configured redirections\n(Not necessarily enabled)"
			: "No redirections configured",
		{
			as: "informational",
			message: redirections,
		},
	);
	return true;
}
function originModal() {
	try {
		const origin = app.displayDialog(
			"URLs begining with this prefix will be opened in Photos.\n(http:// will pre prepended if the scheme is not entered here.)",
			{
				defaultAnswer: config.get("origin"),
				hiddenAnswer: false,
				buttons: ["Cancel", "OK"],
				defaultButton: "OK",
				cancelButton: "Cancel",
				withTitle: "Set origin",
			},
		);
		config.set(
			"origin",
			"http://" + origin.textReturned.replace(/^.*\//, ""),
		);
	} catch {
		// ignore error
	}
	return true;
}

function browserList() {
	const ws = $.NSWorkspace.sharedWorkspace;
	const appURLs = ws.URLsForApplicationsToOpenURL(
		$.NSURL.URLWithString($("https://apple.com")),
	);
	return appURLs.js
		.map((url) => {
			const name =
				$.NSFileManager.defaultManager.displayNameAtPath(
					url.path,
				);
			// Force a native JS string primitive
			return String(ObjC.unwrap(name));
		})
		.filter((name) => name !== "Photos Server");
}
function browserModal() {
	const browser = app.chooseFromList(browserList(), {
		withTitle: "Select Default Browser",
		withPrompt: "Pick one",
		defaultItems: [config.get("browser")],
		okButtonName: "Select",
		cancelButtonName: "Cancel",
		multipleSelectionsAllowed: false,
		emptySelectionAllowed: false,
	});
	if (browser !== false) {
		config.set("browser", String(browser[0]));
	}
	return true;
}

function portModal(errorMessage = "Select the port") {
	try {
		const port = app.displayDialog(errorMessage, {
			defaultAnswer: config.get("port"),
			hiddenAnswer: false,
			buttons: ["Cancel", "OK"],
			defaultButton: "OK",
			cancelButton: "Cancel",
			withTitle: launchAgent.isRunning()
				? "Restart Server"
				: "Start Server",
		});
		if (port.buttonReturned === "OK") {
			try {
				launchAgent.start(port.textReturned);
				pause("Starting server");
			} catch (e) {
				portModal(e.message);
			}
		}
	} catch {
		//
	}
	return true;
}
function run() {
	config.init({
		origin: "http://photos.local",
		browser: "Safari",
		port: "6330",
	});
	primeModal();
}

const config = (() => {
	const d = $.NSUserDefaults.alloc.initWithSuiteName(bid);
	// ensure all defaults have persistent values
	return {
		init: (defaults) =>
			Object.keys(defaults).forEach((key) => {
				if (d.objectForKey(key).isNil())
					d.setObjectForKey($(defaults[key]), key);
			}),
		get: (key) => d.objectForKey(key).js,
		set: (key, value) => d.setObjectForKey($(value), key),
	};
})();
