#!/usr/bin/osascript -l JavaScript
// Copyright (c) 2024 Erik Ben Heckman, shared under the GPL-3.0 license
// <https://github.com/heckman/photos-server>
//
//
//  captures links to media items selected in Apple Photos
//
//
//

// required resources, relative to the Resources folder
const resources = {
	cli: ["serverctl"],
	icon: ["AppIcon", "icns"],
	defaults: ["defaults", "plist"],
	homepage: ["homepage", "webloc"],
	redirections: ["redirections"],
};

ObjC.import("AppKit");

const app = Application.currentApplication();
app.includeStandardAdditions = true;

const bundle = $.NSBundle.bundleWithPath(
	// .stringByDeletingLastPathComponent // Scripts
	$.NSProcessInfo.processInfo.arguments.objectAtIndex(3)
		.stringByDeletingLastPathComponent // Resources
		.stringByDeletingLastPathComponent // Contents
		.stringByDeletingLastPathComponent, // My.app
);
if (bundle.isNil()) throw new Error("Bundle Not Found");

const resource = ((bundle) => {
	return (name, ext = $()) => {
		const filename = resources[name] || [name];
		const path = ((name, ext = $()) =>
			bundle.pathForResourceOfType(name, ext))(...filename);
		if (path.isNil()) {
			throw new Error(
				`Resource Not Found: '${name}' is not in '${bundle.bundlePath.js}/Contents/Resources'`,
			);
		}
		return path.js;
	};
})(bundle);

/**
 * A wrapper to set and get user defaults.
 * It lazily registers fallback values from the given plist file.
 *
 * @typedef {Object} ConfigManager
 * @property {function(string): any} get - Retrieves and unwraps a value from defaults.
 * @property {function(string, any): void} set - Wraps and saves a value to defaults.
 *
 * @type {ConfigManager}
 * @param {$.NSBundle} bundle - The bundle to use for settings.
 * @param {string} fallbackPlistPath - The path to the plist file.
 */
const config = ((defaults, fallbackPlistPath) => {
	let fallbacksExhausted = !fallbackPlistPath;
	function registerFallbacks() {
		defaults.registerDefaults(
			$.NSDictionary.dictionaryWithContentsOfFile(
				fallbackPlistPath,
			),
		);
		fallbacksExhausted = true;
	}
	return {
		get: (key) => {
			let value = defaults.objectForKey(key);
			if (value.isNil()) {
				if (fallbacksExhausted) return null;
				registerFallbacks();
				value = defaults.objectForKey(key);
				if (value.isNil()) return null;
			}
			return ObjC.deepUnwrap(value);
		},
		set: (key, value) => {
			defaults.setObjectForKey($(value), key);
		},
	};
})(
	$.NSUserDefaults.alloc.initWithSuiteName(bundle.bundleIdentifier),
	resource("defaults"),
);

const launchAgent = ((serverctl) => {
	const execute = (cmd) => app.doShellScript(`'${serverctl}' ${cmd}`);
	return {
		status: () => execute("status"),
		start: (port) => execute(`start ${port}`),
		stop: () => execute("stop"),
		port: () => execute("port"),
		forwarding: () => execute("forwarding"),
		isRunning: () => {
			try {
				execute("test");
				return true;
			} catch {
				return false;
			}
		},
	};
})(resource("cli"));

function run(args) {
	primeModal();
}

function readPlist(plistFile) {
	return ObjC.deepUnwrap(
		$.NSDictionary.dictionaryWithContentsOfFile(plistFile),
	);
}

function pause(message) {
	return infobox(message, 1.5);
}
function infobox(message, timeout = 0) {
	app.displayDialog(message, {
		withTitle: "Photos Server",
		withIcon: Path(resource("icon")),
		givingUpAfter: timeout, // Dismisses after 1 second
		buttons: ["Dismiss"],
		defaultButton: "Dismiss",
	});
}

function primeModal() {
	const browser = config.get("browser");
	const origin = config.get("origin");
	const port = launchAgent.port();
	const redirections = launchAgent.forwarding().trim();
	const choices = {
		restart: { label: "Change the port", action: portModal },
		remove: {
			label: "Disable the server",
			action: () => {
				launchAgent.stop();
				pause("Disabling server");
				return true;
			},
		},
		start: { label: "Enable the server", action: portModal },
		origin: {
			label: "Set URL prefix that will open in Photos",
			action: originModal,
		},
		browser: {
			label: "Set browser for everything else",
			action: browserModal,
		},
		redirections: {
			label: "Display configured redirections",
			action: () => redirectionsModal(redirections),
		},
		homepage: {
			label: "Visit Photos Server homepage and close",
			action: () => {
				pause("Opening homepage...");
				$.NSWorkspace.sharedWorkspace.openFile(
					resource("homepage"),
				);
				return false;
			},
		},
	};

	let list = launchAgent.isRunning()
		? [choices.restart.label, choices.remove.label]
		: [choices.start.label];
	let status = `${launchAgent.status()}

Links beginning with "${origin}"
will open in Photos.

Everything else will open in ${browser}.`;

	list = [...list, choices.origin.label, choices.browser.label];

	if (redirections) list = [...list, choices.redirections.label];

	list = [...list, choices.homepage.label];

	const choice = app.chooseFromList(list, {
		withTitle: "Photos Server Control",
		withPrompt: status,
		defaultItems: [],
		okButtonName: "Select",
		cancelButtonName: "Done",
		multipleSelectionsAllowed: false,
		emptySelectionAllowed: false,
	});
	if (choice === false) return;
	if (
		Object.values(choices)
			.find((c) => c.label === choice[0])
			.action()
	)
		primeModal();
}

function redirectionsModal(redirections) {
	infobox(
		redirections
			? "These redirections are configured, but not necessarily enabled.\n\n" +
					redirections
			: "No redirections configured",
	);
	return true;
}
function originModal() {
	try {
		const origin = app.displayDialog(
			"URLs begining with this prefix will be opened in Photos.\n(http:// will pre prepended if the scheme is not entered here.)",
			{
				defaultAnswer: config.get("origin"),
				hiddenAnswer: false,
				buttons: ["Cancel", "OK"],
				defaultButton: "OK",
				cancelButton: "Cancel",
				withTitle: "Photos Server: Set Origin",
			},
		);
		config.set(
			"origin",
			"http://" + origin.textReturned.replace(/^.*\//, ""),
		);
	} catch {
		// ignore error
	}
	return true;
}

function browserList() {
	const appURLs =
		$.NSWorkspace.sharedWorkspace.URLsForApplicationsToOpenURL(
			$.NSURL.URLWithString($("https://apple.com")),
		);
	return appURLs.js
		.map((url) => {
			const name =
				$.NSFileManager.defaultManager.displayNameAtPath(
					url.path,
				);
			// Force a native JS string primitive
			return String(ObjC.unwrap(name));
		})
		.filter((name) => name !== "Photos Server");
}
function browserModal() {
	const browser = app.chooseFromList(browserList(), {
		withTitle: "Photos Server Preferences",
		withPrompt: "Select Default Browser",
		defaultItems: [config.get("browser")],
		okButtonName: "Select",
		cancelButtonName: "Cancel",
		multipleSelectionsAllowed: false,
		emptySelectionAllowed: false,
	});
	if (browser !== false) {
		config.set("browser", String(browser[0]));
	}
	return true;
}

function portModal(errorMessage = "Select the port") {
	try {
		const port = app.displayDialog(errorMessage, {
			defaultAnswer: config.get("port"),
			hiddenAnswer: false,
			buttons: ["Cancel", "OK"],
			defaultButton: "OK",
			cancelButton: "Cancel",
			withTitle: launchAgent.isRunning()
				? "Photos Server: Change Listening Port"
				: "Photos Server: Enable Server",
		});
		if (port.buttonReturned === "OK") {
			try {
				launchAgent.start(port.textReturned);
				pause("Enabling server");
			} catch (e) {
				portModal(e.message);
			}
		}
	} catch {
		//
	}
	return true;
}

function openURL(url) {
	$.NSWorkspace.sharedWorkspace.openURL($.NSURL.URLWithString(url));
}
