#!/usr/bin/osascript -l JavaScript

ObjC.import("Foundation");

const FILE_MANAGER = $.NSFileManager.defaultManager;
const TEMP_DIR_TEMPLATE = "ca.heckman.PhotoServer.exported-media-item.";
const CURRENT_APPLICATION = Application.currentApplication();
CURRENT_APPLICATION.includeStandardAdditions = true;

const logError = (error) => console.log(error);
const debug = (message) => null; //console.log(message);

function run(args) {
	const tempDir = createTemporaryDirectory(TEMP_DIR_TEMPLATE);
	if (tempDir) {
		try {
			handle_http_request(slurpStdin(), tempDir);
		} catch (error) {
			logError(error);
			reply500();
		} finally {
			deleteDirectory(tempDir);
		}
	} else {
		logError("failed to create temporary directory");
		reply500();
	}
}

function handle_http_request(stdin, tempDir) {
	debug("stdin: " + stdin);
	debug("tempDir: " + tempDir);

	const urlComponents = stdin.split("\n").at(0).split("/").slice(1);
	const identifier = urlComponents.at(0).replace(/[+.~]/g, " ");
	const basename = urlComponents.at(-1) || urlComponents.at(-2);
	debug("identifier: " + identifier);
	debug("basename: " + basename);

	if (!exportMediaItemFromPhotos(identifier, tempDir))
		return reply404();
	const exportedFilename = directoryContents(tempDir)?.at(0);

	if (!exportedFilename)
		throw new Error("Failed to find exported file");

	const filename =
		basename + "." + exportedFilename.split(".").at(-1);
	const filepath = tempDir + "/" + exportedFilename;
	return reply(
		[
			"HTTP/1.1 200 OK",
			`Content-Type: ${mimeType(filepath)}`,
			`Content-Length: ${fileSize(filepath)}`,
			`Content-Disposition: inline; filename=${filename}`,
		],
		"",
		filepath,
	);
}

function exportMediaItemFromPhotos(identifier, tempDir) {
	const photos = Application("Photos");
	const exportItem = (item) => {
		photos.export([item], {
			to: Path(tempDir),
			usingOriginals: false,
		});
	};
	try {
		debug("UUID: " + identifier);
		exportItem(photos.mediaItems.byId(identifier));
		return true;
	} catch {
		try {
			debug("query: " + identifier);
			exportItem(photos.search({ for: identifier })[0]);
			return true;
		} catch {
			return false;
		}
	}
}

slurpStdin = () =>
	$.NSString.alloc.initWithDataEncoding(
		$.NSFileHandle.fileHandleWithStandardInput.readDataToEndOfFile,
		$.NSUTF8StringEncoding,
	).js;

const createDirectory = (path) =>
	FILE_MANAGER.createDirectoryAtPathWithIntermediateDirectoriesAttributesError(
		path,
		true,
		$.nil,
		$.nil,
	)
		? path
		: null;

// returning boolean version
const deleteDirectory = (directory) =>
	FILE_MANAGER.removeItemAtPathError(directory, $.nil);

const createTemporaryDirectory = (template = "") =>
	createDirectory(
		$.NSTemporaryDirectory().js +
			template +
			$.NSUUID.UUID.UUIDString.js,
	);

const directoryContents = (directory) =>
	((files) =>
		files && !files.isNil() ? ObjC.deepUnwrap(files) : null)(
		FILE_MANAGER.contentsOfDirectoryAtPathError(directory, $.nil),
	);

const mimeType = (filePath) =>
	CURRENT_APPLICATION.doShellScript(
		`file -b --mime-type '${filePath.replace(/\'/g, "'\\''")}' | grep -v '^cannot'`,
	) || null;

const fileSize = (filePath) =>
	((attributes) =>
		!attributes.isNil()
			? attributes.objectForKey($.NSFileSize).js
			: null)(
		FILE_MANAGER.attributesOfItemAtPathError(filePath, $.nil),
	);

function reply(headers, text, filePath = null) {
	const stringContent = headers.join("\r\n") + "\r\n\r\n" + text;
	const stdOut = $.NSFileHandle.fileHandleWithStandardOutput;
	stdOut.writeData(
		$.NSString.alloc
			.initWithString(String(stringContent))
			.dataUsingEncoding($.NSUTF8StringEncoding),
	);
	if (filePath)
		stdOut.writeData($.NSData.dataWithContentsOfFile(filePath));
	// stdOut.closeFile();
}

const reply200 = (filepath, filename) =>
	reply(
		[
			"HTTP/1.1 200 OK",
			`Content-Type: ${fileType(filepath)}`,
			`Content-Length: ${fileSize(filepath)}`,
			`Content-Disposition: inline; filename=${filename || filepath.split("/").at(-1)}`,
		],
		"",
		filepath,
	);

const replySvg = (responseCode, svg) => {
	reply(
		[
			"HTTP/1.1 " + responseCode,
			"Content-Type: image/svg+xml",
			"Content-Length: " + svg.length,
		],
		svg,
	);
};

const reply404 = () =>
	replySvg(
		"404 Not Found",
		`<?xml version="1.0" encoding="UTF-8"?>
<!-- old school pixellated netscape broken image icon -->
<!--
  icon created for Netscape Navigator by Marsh Chamberlin (https://dataglyph.com)
  SVG hand-coded by github user diachedelic (https://gist.github.com/diachedelic)
  source: https://gist.github.com/diachedelic/cbb7fdd2271afa52435b7d4185e6a4ad
  accessed: 2024-02-12
-->
<svg viewBox="0 0 14 16" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <g id="borders-and-backgrounds">
    <path d="M0,0 L10,0 L10,1 L1,1 L1,15 L2,15 L2,16 L0,16 Z" fill="black"></path>
    <path d="M10,4 l4,0 l0,3 l-1,0 l0,-2 l-3,0 Z" fill="black"></path>
    <path d="M14,16 l0,-6 l-1,0 l0,5 l-5,0 l0,1 Z" fill="black"></path>
    <path d="M12,14 l0,-3 l-1,0 l0,2 l-2,0 l0,1 Z" fill="#bcbcc3"></path>
    <path d="M10,0 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l-1,0 l0,-1 l-1,0 l0,-1 l-1,0 l0,2 l-1,0 Z" fill="#878787">
    </path>
    <path d="M2,2 l8,0 l0,3 l2,0 l0,2 l-4,0 l0,5 l-2,0 l0,1 l-2,0 l0,1 l-2,0 Z" fill="#bcbcc3"></path>
  </g>
  <g id="lefteye">
    <path d="M5,3 l2,0 l0,3 l-3,0 l0,-2 l1,0 l0,1 l1,0 l0,-1 l-1,0 Z" fill="#00891e"></path>
    <path d="M5,4 l1,0 l0,1 l-1,0 Z" fill="#00f248"></path>
    <path d="M7,4 l1,0 l0,2 l-1,0 l0,1 l-2,0 l0,-1 l2,0 Z" fill="black"></path>
  </g>
  <g id="righteye">
    <path d="M8,7 l3,0 l0,2 l-1,0 l0,-1 l-1,0 l0,1 l1,0 l0,1 l-2,0 Z" fill="#0064fb"></path>
    <path d="M9,8 l1,0 l0,1 l-1,0 Z" fill="#00fbfe"></path>
    <path d="M10,9 l1,0 l0,1 l-1,0 Z" fill="#003293"></path>
    <path d="M11,7 l1,0 l0,2 l-1,0 Z" fill="black"></path>
    <path d="M8,10 l2,0 l0,1 l-2,0 Z" fill="black"></path>
  </g>
  <g id="mouth">
    <path d="M3,8 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l-1,0 l0,-1 l-1,0 l0,-1 l-1,0 l0,-1 l-1,0 Z" fill="#ff3900">
    </path>
    <path d="M3,9 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l-3,0 Z" fill="#f73ae1"></path>
    <path d="M3,12 l3,0 l0,1 l-3,0 Z" fill="black"></path>
  </g>
</svg>`,
	);
const reply500 = () =>
	replySvg(
		"500 Internal Server Error",
		`<?xml version="1.0" encoding="UTF-8"?>
<!--
The "Sad Mac" icon was created for Apple Inc. by Susan Kare https://kareprints.com
The SVG was hand-coded Erik Ben Heckman https://erik.heckman.ca
and can be found embedded in the code for https://github.com/heckman/photos-server
-->
<svg viewBox="0 0 37 37" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <path id="mask" fill="#ffffff" d="
    M6,4 h25 v26 h-25 z M7,3 h23 v32 h-23 zM8,2 h 21 v 2 h-21 z"></path>
  <path id="lines" fill-rule="evenodd" fill="black" d="
    M6,4 h25 v26 h-25 z M7,3 h23 v32 h-23 z M8,2 h 21 v 2 h-21 z M8,31 h21 v 3 h-21 Z
    M10,5 h17 v16 h-17 z M9,6 h19 v14 h-19 Z
    M13,9 h1 v3 h-1 v-1 h3 v1 h-1 v-3 h1 v1 h-3 Z
    M21,9 h1 v3 h-1 v-1 h3 v1 h-1 v-3 h1 v1 h-3 Z
    M16,13 h1 v2 h2 v-2 h1 v1 h-4 Z
    M16,16 h5 v2 h3 v1 h-1 v-2 h-8 v 1 h 1 Z
    M9,26 h2 v1 h-2 Z
    M21,25 h6 v1 h-6 Z"></path>
</svg>`,
	);
const reply504 = () =>
	replySvg(
		"504 Gateway Timeout",
		`<?xml version="1.0" encoding="UTF-8"?>
<!--
The "Watch" cursor was created for Apple Inc. by Susan Kare https://kareprints.com
The SVG was hand-coded Erik Ben Heckman https://erik.heckman.ca who added the exclaimation
point and can be found embedded in the code for https://github.com/heckman/photos-server
-->
<svg viewBox="-2 -6 30 30" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <rect id="face" x="5" y="5" width="8" height="8" fill="white" />
  <path id="watch" fill-rule="evenodd" fill="black" d="
    M 6 1 h 6 v 16 h -6 Z
    M 4 6 h 10 v 6 h -10 Z
    M 5 5 h 8 v 8 h -8 Z
    M 6 6 h 6 v 6 h -6 Z
    M 14 8 h 1 v 2 h -1 Z
    M 9 6 h 1 v 4 h -3 v -1 h 2 Z
  "></path>
  <path id="bang" fill-rule=" evenodd" fill="#eb161e" d="
    M 18 1 v16 h 3 v -4 h -3 v 1 h 3 v -13 Z
  "></path>"
</svg>`,
	);
