#!/bin/sh

# This prints redirections configured by the Photos Server daemon:
daemon=ca.heckman.PhotosServer.port-forwarding

# If provided a hostname as an argument, it will be looked up in /etc/hosts
# and used to substitute matching ip addresses.


# default for $1 is '$$' so it won't match anything in /etc/hosts
# eacg . character is escaped for use in a regular expression (not $ though)
hostregex=$(
	/bin/echo "[[:space:]]${1:-\$\$}\$" | /usr/bin/sed -E 's/\./\\./g'
)

# sed commands to replace ip addresses with hostname defined in /etc/hosts
subs="$(
	/usr/bin/awk "/${hostregex}/"'{printf("s/%s/%s/;",$1,$2)}' /etc/hosts
)"

# add sed commands to replace localhost ip addresses with 'localhost'
subs="${subs}s/127.0.0.1:/localhost:/;s/::1:/localhost:/;"


# extract the hosts and ports from the forwarding rule
# defined in the launchdaemon, then apply sub substitutions
#
# shellcheck disable=SC2046  # subshell output splits on whitespace
/usr/bin/printf "IP4:%s🠪%s\nIP6:%s🠪%s\n" $(
	/bin/launchctl print "system/$daemon" |
	/usr/bin/grep -- '->' |
	/usr/bin/sed -E 's/^.* ([0-9.]+) port ([0-9]+) -> ([0-9.]+) port ([0-9]+)\\.* ([a-fA-F0-9:]+) port ([0-9]+) -> ([a-fA-F0-9:]+) port ([0-9]+)\\.*$/\1:\2 \3:\4 \5:\6 \7:\8/;'"${subs}"
)
