#!/bin/sh

set -eu

source_dir="$(git rev-parse --show-toplevel)/src/port-forwarding"

label="ca.heckman.PhotosServer.port-forwarding"
anchor="com.apple/ca.heckman.PhotosServer"

# these should not be changed
plist_file="$label.plist"
source_plist="$source_dir/$plist_file"
installed_launch_daemon="/Library/LaunchDaemons/$plist_file"


if ! test -f  "$source_plist"
then
	echo "Could not find plist for launch daemon at '$source_plist'."
	exit 1
fi

if \
sudo cp -i "$source_plist" "$installed_launch_daemon"
then
	# this will fail if the daemon isn't actually loaded
	sudo launchctl bootout "system/$label" >/dev/null 2>&1 || :
	# not that the daemon is definately not loaded this should not fail
	sudo launchctl bootstrap system  "$installed_launch_daemon" &&
	sudo pfctl -q -a "$anchor" -s nat |
	sed -E 's/^.* ([0-9.]*) port[ =]*([0-9]*) -> ([0-9.]*) port ([0-9.]*).*$/Requests to \1:\2 should now be forwarded to \3:\4/' &&
	exit 0
fi
echo Port-forwarding failed or aborted.
exit 1

