#!/usr/bin/env bash

set -euo pipefail

#: Make Favicons from the icon of an Application

usage="
app-favicons: make Favicons from the icon of an application

  Usage: $0 <Application> [target-directory]

The required argument is the name of an Application.
The target directory defaults to the current  working directory.

The following files will be created in the target directory:

  - apple-touch-icon.png
  - favicon.png
  - favicon.ico

The .ico file will only be created if image magick is available.

"

die() { echo "$1" >&2; exit "${2:-1}"; }


[[ -n "${1:-}" ]] || die "$usage"
if [[ -n "${2:-}" ]]
then
	mkdir -p "$2" || die "Can't make directory: $2"
 	cd "$2" || die "Can't change to directory: $2"
fi

package="$(
	osascript -e '
tell app "System Events" to POSIX path of (path to app "'"$1"'")
' 2>/dev/null
	)" || die "Can't find application: $1"

resources="$package/Contents/Resources"
icns="$(
		find "$resources" -name '*.icns' -print -quit |
		grep -F ''
	)" || die "Can't find icons: $icns"

tmpdir="$(mktemp -d -t appFavIcon)" ||
	die "Can't make temporary directory"
# shellcheck disable=SC2064  # we want to expand tmpdir now
trap "rm -rf '$tmpdir'" EXIT

iconset="$tmpdir/iconset.iconset"
iconutil --convert iconset -o "$iconset" "$icns" ||
	die "Can't convert icns"

largest=$(
	du -a "$iconset"/* |
	sort -nr |
	head -n1 |
	sed 's/^[0-9]*[[:space:]]*//'
)

exists(){
	[[ -e "$1" ]] || return 1
	echo "Not overwriting existing $1"
	return 0
}

# use the largest png as a favicon
#
exists favicon.png || cp "$largest" favicon.png

# create an apple-touch icon
#
exists  apple-touch-icon.png ||
sips --resampleHeightWidthMax 180 --out apple-touch-icon.png "$largest"

# if image magick is available, also make an .ico file
#
if command -v magick >/dev/null 2>&1
then
	exists favicon.ico ||
	magick "$iconset"/* favicon.ico
fi
