#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 Erik Ben Heckman <erik@heckman.ca>

# danger
#
# an installer of dangerous extras for Photos Server

# Use this script at your own risk.
# It is dangerous.
# Except for the plist command, which is safe.
#
# The plist command will print the plist which
# is installed to enable port-forwarding.
#
# It is provided should you like to do so manually


# these should match the origin and port settings
# in the Photos Server application, respectively,
# only there is no scheme here, i.e. no http:// prefix.
hostname=photos.local
port=6330

# after adding the hostname to /etc/hosts and
# enabling port-forwarding, you should be able
# to access the Photos Server running on http://localhost:<port>
# at the address http://<hostname>



# this should be a loopback address other than 127.0.0.1,
# which will likely be used by a web server.
# it can be set to anything else starting with `127.`
# it is unlikely this will need to be changed.
ip4address=127.6.3.3
ip6address=fd00::6630

set -eu

usage="Usage: ${0##*/} host|forwarding|plist [subcommand]
              ${0##*/} ok install|uninstall

commands:
	host         manage /etc/hosts
	forwarding   manage port-forwarding
	plist        print the port-forwarding plist
	             (not dangerous)
ok subcommands:
	install        enable port-forwarding and
	               add host to /etc/hosts
	ok uninstall   uninstall port-forwarding and
	               remove host from /etc/hosts

For more information for hosts and forwarding commands, use
	${0##*/} [command] --help

"

main(){
	case "${1:-}" in
	host) host_main "${2:-}" ;;
	forwarding) forwarding_main "${2:-}" ;;
	plist) plist_main;;
	ok) ok_main "${2:-}" ;;
	-h|--help|help)
		case "${2:-}" in
		host) ok "$host_usage" ;;
		forwarding) ok "$forwarding_usage" ;;
		plist) ok "$plist_usage" ;;
		*) ok "$usage" ;;
		esac ;;
	*) die "$usage" 2;;
	esac
}

die() {
	echo "$1" >&2
	exit "${2:-1}";
}
ok() {
	echo "$1"
	exit 0;
}

host_usage="
usage: ${0##*/} host [test|status|add|remove]
subcommands:
	test    exits with 0 status if $hostname is in /etc/hosts,
	        otherwise exits with 1.
	        other commands exit 0 on success, 1 on failure
	status  print the host address for $hostname
	add     add $hostname to /etc/hosts as $ip4address and $ip6address
	remove  remove $hostname from /etc/hosts

"

host_main(){

	# just in case the scheme is included in the hostname set earlier
	hostname="${hostname##*/}"

	case "$1" in
	test) is_in_hosts ;;
	status) print_host_addresses ;;
	add) add_hostname ;;
	remove) remove_hostname ;;
	-h|--help|help) ok "$host_usage" ;;
	*) die "$host_usage" 2;;
	esac
}

print_host_addresses(){
	grep "[[:space:]]${hostname}\$" /etc/hosts
}

add_hostname(){
	if grep -qi "^[0-9].*[[:space:]]${hostname}\$" /etc/hosts
	then
		echo "$hostname is already in /etc/hosts as $ip4address"
	else
		printf '%-16s%s\n' "$ip4address" "$hostname" |
		sudo tee -a /etc/hosts >/dev/null ||
		die "failed to add $hostname to /etc/hosts as $ip4address"
		echo "added $hostname to /etc/hosts as $ip4address"
	fi
	if grep -qi "^[a-f].*[[:space:]]${hostname}\$" /etc/hosts
	then
		echo "$hostname is already in /etc/hosts as $ip6address"
	else
		printf '%-16s%s\n' "$ip6address" "$hostname" |
		sudo tee -a /etc/hosts >/dev/null ||
		die "failed to add $hostname to /etc/hosts as $ip6address"
		echo "added $hostname to /etc/hosts as $ip6address"
	fi

}
remove_hostname(){
	grep -qi "[[:space:]]${hostname}\$" /etc/hosts || ok "$hostname is not in /etc/hosts"
	# shellcheck disable=SC2015  # ok exits, so A && B || C is fine
	hosts=$(cat /etc/hosts) &&
	printf '%s' "$hosts" |
	grep -v "[[:space:]]${hostname}\$" |
	sudo tee /etc/hosts >/dev/null &&
		ok "$hostname has been removed from /etc/hosts" ||
		die "failed to remove $hostname from /etc/hosts"
}

forwarding_usage="usage: ${0##*/} forwarding [test|status|enable|disable]

subcommands:
	test    exits with 0 status if port-forwarding is active,
	        otherwise exits with 1.
	        other commands exit 0 on success, 1 on failure
	status  print status of port-forwarding
	enable  enable port-forwarding
	disable disable port-forwarding
"

# the following should not be changed
pf_anchor="com.apple/ca.heckman.PhotosServer"
daemon_label="ca.heckman.PhotosServer.port-forwarding"
installed_launch_daemon="/Library/LaunchDaemons/$daemon_label.plist"

forwarding_main () {
	case "${1:-}" in
	test) is_forwading ;;
	print) print_forwarding ;;
	plist) print_forwarding_plist ;;
	flush) forwading_flush ;;
	status) forwarding_status ;;
	enable) enable_port_forwarding ;;
	disable) disable_port_forwarding ;;
	-h|--help|help) ok "$forwarding_usage" ;;
	*) die "$forwarding_usage" 2;;
	esac
}
print_forwarding_plist(){
	cat "$installed_launch_daemon"
}
print_forwarding(){
	sudo pfctl -q -a "$pf_anchor" -s nat
}
forwarding_status(){
	print_forwarding |
	sed -E 's/^.* ([0-9.]*) port[ =]*([0-9]*) -> ([0-9.]*) port ([0-9.]*).*$/Requests to \1:\2 should be forwarded to \3:\4/' |
	grep . || echo "Photos Server port-forwarding is disabled."
}
is_forwading(){
	print_forwarding |
	grep -q .
}
forwading_bootout(){
	if is_forwading
	then sudo launchctl bootout "system/$daemon_label"
	fi
}
forwarding_bootstrap(){
	sudo launchctl bootstrap system "$installed_launch_daemon"
}
forwading_flush(){
	sudo pfctl -a "$pf_anchor" -F all > /dev/null 2>&1
}
enable_port_forwarding(){
	print_plist | sudo tee "$installed_launch_daemon" >/dev/null ||
		die "Failed to write plist to '$installed_launch_daemon'"
	forwading_bootout ||
		die "Could not disable existing port-forwarding"
	forwarding_bootstrap ||
		die "Could not enable port-forwarding"
	sleep 0.5
	forwarding_status
}
disable_port_forwarding(){
	forwading_bootout ||
		die "Could not disable port-forwarding"
	forwading_flush ||
		die "Failed to flush port-forwarding rules"
	if test -f "$installed_launch_daemon"
	then sudo rm "$installed_launch_daemon" ||
		die "Failed to remove launch daemon plist at '$installed_launch_daemon'"
	fi
	! is_forwading ||
		die "Error: Port forwarding is still active"
	echo "Photo Server port forwarding is uninstalled."
}

plist_usage="usage: ${0##*/} plist [test|status|enable|disable]

This prints the plist for the launch daemon.
It has no subcommands.
It is not dangerous.

"

plist_main(){
	print_plist
}

print_plist(){
	cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>${daemon_label}</string>
        <key>ProgramArguments</key>
        <array>
            <string>/bin/sh</string>
            <string>-c</string>
            <string>/usr/bin/printf "rdr pass on lo0 inet proto tcp from any to %s port 80 -> 127.0.0.1 port %s\nrdr pass on lo0 inet6 proto tcp from any to %s port 80 -> ::1 port %s\n" "${ip4address}" "${port}" "${ip6address}" "${port}" | /sbin/pfctl -a ${pf_anchor} -f -</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <false/>
        <key>UserName</key>
        <string>root</string>
    </dict>
</plist>
EOF

}

ok_main(){
	case "${1:-}" in
	install) enable_port_forwarding && add_hostname ;;
	uninstall) disable_port_forwarding && remove_hostname ;;
	*) die "$usage" 2;;
	esac
}

test -f "$(git rev-parse --show-toplevel)/.danger_ok~" ||
{
	echo "READ THE SOURCE"
	exit 1
}

main "$@"
