#!/usr/bin/env bash

set -euo pipefail

# work from project root
cd "$(git rev-parse --show-toplevel)" || exit 1

# remove any existing builds
rm -rf dist/Photos\ Server.app

# this builds and signs the bundle
osabundle src/photosServer.json

# remove any existing install
rm -rf "/Applications/Photos Server.app"

# install
mv dist/Photos\ Server.app /Applications

# force reregistration
# /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -f /Applications/Photos\ Server.app

