#!/usr/bin/env bash

set -euo pipefail

# work from project root
cd "$(git rev-parse --show-toplevel)" || exit 1

# this builds and signs the bundle
script-bundler photos-launcher.json dist/Photos\ Launcher.app


rm -rf "/Applications/Photos Launcher.app"

mv dist/Photos\ Launcher.app /Applications


## force reregistration
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -f /Applications/Photos\ Launcher.app

