#!/opt/homebrew/bin/bash
# Copyright (c) 2024 Erik Ben Heckman, shared under the GPL-3.0 license
# except where otherwise noted
# <https://github.com/heckman/photos-server>
#
#
#  photos-http-handler
#
#
# Serves photos from Apple Photos.

# Responds to http requests from stdin, where the root of the url
# path is either the UUID of a media item in Apple Photos or a
# search query.
#
# If a matching media item is found, it prints, to stdout, a HTTP
# response with the media item as inline content. If multiple
# matching media items are found, an arbitrary one is chosen.
#
# IF no item is found, or Apple Photos times out during the request,
# then a 404 HTTP response is printed with a placeholder image.
#
# If something unexpected occurs, a 500 HTTP resonse is printed
# with a placeholder image.

set -e

# shellcheck disable=SC2034
silent=0  error=1 warn=3 info=4 debug=5
vebosity=$info


# dependencies can be installed via homebrew:
#   brew bash install jq coreutils
#
# when this handleris run the ath is /usr/bin:/bin:/usr/sbin:/sbin
# so we need to locate out dependencies
TIMEOUT=/opt/homebrew/bin/timeout
JQ=/opt/homebrew/bin/jq
# the location of bash also needs to be specified in the shebang
# bash needs to support associative arrays, which is in bash 4.0

TEMP_TEMPLATE=ca.heckman.photos-server.image
TIMEOUT_SECONDS=12  # time given to Photos to respond to request


main(){
	local method path protocol
	# shellcheck disable=SC2034  # not using method or protocol
	read -r method path protocol

	info "Request path: $path"

	local -a url_components
	while read -r part
	do
		part="${part//[+.~]/ }"
		url_components+=("$(printf '%b' "${part//%/\\x}")")
	done < <(tr / $'\n' <<< "$path")

	local query="${url_components[1]}"
	local basename="${url_components[-1]}"

	debug "Query: $query"
	debug "Basename: $basename"

	local tmpdir
	tmpdir="$(mktemp -d -t $TEMP_TEMPLATE)" || die ERR_TEMP
	# shellcheck disable=SC2064  # we want to expand tmpdir now
	trap "rm -rf '$tmpdir'" EXIT

	local result
	result="$(export_media_item_from_photos "$query" "$tmpdir")" ||
		case $? in
		124) die ERR_TIMEOUT 504;;
		1) die ERR_JXA ;;
		*) die ;;
		esac

	debug "Result=$result"
	[[ -n "$result" ]] || {
		info "No matching media items."
		canned_response 404
		exit 0
	}

	local filename filesize filetype extension
	filename="$(any_file_in "$tmpdir")" || die ERR_EXPORT
	filesize="$(stat -f'%z' "$filename")"
	filetype="$(file -b --mime-type "$filename")"
	extension="${filename##*.}"

	info "Serving 200 OK: $basename.$extension"

	echo "HTTP/1.1 200 OK
Content-Type: $filetype
Content-Length: $filesize
Content-Disposition: inline; filename=$basename.$extension
"; cat "$filename";

	exit 0
}



die(){
	local -A error_messages=(
		[ERR_TEMP]="Failed to create temporary directory"
		[ERR_JXA]="Failed to run jxa"
		[ERR_EXPORT]="Failed to find exported file"
		[ERR_TIMEOUT]="Request to Photos timed out."
	)
	error "${error_messages[$1]:-Unknown error}"
	canned_response "${2:-500}"
	exit 1
}

canned_response(){
	local description filename
	case "$1" in
	404)
		description="Not Found"
		filename="missing.svg";;
	500)
		description="Internal Server Error"
		filename="error.svg";;
	504)
		description="504 Gateway Timeout"
		filename="timeout.svg";;
	esac
	local content="${canned_responses[$2]}"
	local length="${#content}"
	# all canned responses are svg images
	local content_type="svg+xml"

	info "Serving $1: $filename"

	echo -n "HTTP/1.1 $1 $description
Content-Type: $content_type
Content-Length: $length
Content-Disposition: inline; filename=$filename

$content";
}

any_file_in(){
	find "$1" -maxdepth 1 -type f ! -name '.*' 2>/dev/null | grep -F ''
}

log(){ date +"%Y-%m-%d %H:%M:%S $1" >&2; }
debug(){ [[ $vebosity -lt $debug ]] || log "[ DEBUG ]  $1"; }
info(){ [[ $vebosity -lt $info ]] || log "[ INFO ]  $1"; }
error(){ [[ $vebosity -lt $error ]] || log "[ ERROR ]  $1"; }

export_media_item_from_photos(){ local query="$1" tmpdir="$2"
	local jxa="$(cat <<EOF
(
	(args)=>{
		app=Application("Photos");
		exportItem=(item)=>{
			app.export(
				[item], {
					to:Path(args[1]),
					usingOriginals: false
				}
			)
		}
		try{
			exportItem(app.mediaItems.byId(args[0]))
			return true
		} catch {
			try {
				exportItem(app.search({for:args[0]})[0])
				return true
			} catch {
				return
			}
		}
	}
)( $("$JQ" -Rn '[inputs]' <<<"$query
$tmpdir") )
EOF
)"
	debug "$jxa"
	"$TIMEOUT" "$TIMEOUT_SECONDS" /usr/bin/osascript -l JavaScript -e "$jxa"
}

declare -A canned_responses=(
	["missing.svg"]='<?xml version="1.0" encoding="UTF-8"?>
<!-- old school pixellated netscape broken image icon -->
<!--
  icon created for Netscape Navigator by Marsh Chamberlin (https://dataglyph.com)
  SVG hand-coded by github user diachedelic (https://gist.github.com/diachedelic)
  source: https://gist.github.com/diachedelic/cbb7fdd2271afa52435b7d4185e6a4ad
  accessed: 2024-02-12
-->
<svg viewBox="0 0 14 16" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <g id="borders-and-backgrounds">
    <path d="M0,0 L10,0 L10,1 L1,1 L1,15 L2,15 L2,16 L0,16 Z" fill="black"></path>
    <path d="M10,4 l4,0 l0,3 l-1,0 l0,-2 l-3,0 Z" fill="black"></path>
    <path d="M14,16 l0,-6 l-1,0 l0,5 l-5,0 l0,1 Z" fill="black"></path>
    <path d="M12,14 l0,-3 l-1,0 l0,2 l-2,0 l0,1 Z" fill="#bcbcc3"></path>
    <path d="M10,0 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l-1,0 l0,-1 l-1,0 l0,-1 l-1,0 l0,2 l-1,0 Z" fill="#878787">
    </path>
    <path d="M2,2 l8,0 l0,3 l2,0 l0,2 l-4,0 l0,5 l-2,0 l0,1 l-2,0 l0,1 l-2,0 Z" fill="#bcbcc3"></path>
  </g>
  <g id="lefteye">
    <path d="M5,3 l2,0 l0,3 l-3,0 l0,-2 l1,0 l0,1 l1,0 l0,-1 l-1,0 Z" fill="#00891e"></path>
    <path d="M5,4 l1,0 l0,1 l-1,0 Z" fill="#00f248"></path>
    <path d="M7,4 l1,0 l0,2 l-1,0 l0,1 l-2,0 l0,-1 l2,0 Z" fill="black"></path>
  </g>
  <g id="righteye">
    <path d="M8,7 l3,0 l0,2 l-1,0 l0,-1 l-1,0 l0,1 l1,0 l0,1 l-2,0 Z" fill="#0064fb"></path>
    <path d="M9,8 l1,0 l0,1 l-1,0 Z" fill="#00fbfe"></path>
    <path d="M10,9 l1,0 l0,1 l-1,0 Z" fill="#003293"></path>
    <path d="M11,7 l1,0 l0,2 l-1,0 Z" fill="black"></path>
    <path d="M8,10 l2,0 l0,1 l-2,0 Z" fill="black"></path>
  </g>
  <g id="mouth">
    <path d="M3,8 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l-1,0 l0,-1 l-1,0 l0,-1 l-1,0 l0,-1 l-1,0 Z" fill="#ff3900">
    </path>
    <path d="M3,9 l1,0 l0,1 l1,0 l0,1 l1,0 l0,1 l-3,0 Z" fill="#f73ae1"></path>
    <path d="M3,12 l3,0 l0,1 l-3,0 Z" fill="black"></path>
  </g>
</svg>
'
	["error.svg"]='<?xml version="1.0" encoding="UTF-8"?>
<!--
The "Sad Mac" icon was created for Apple Inc. by Susan Kare https://kareprints.com
The SVG was hand-coded Erik Ben Heckman https://erik.heckman.ca
and can be found embedded in the code for https://github.com/heckman/photos-server
-->
<svg viewBox="0 0 37 37" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <path id="mask" fill="#ffffff" d="
    M6,4 h25 v26 h-25 z M7,3 h23 v32 h-23 zM8,2 h 21 v 2 h-21 z"></path>
  <path id="lines" fill-rule="evenodd" fill="black" d="
    M6,4 h25 v26 h-25 z M7,3 h23 v32 h-23 z M8,2 h 21 v 2 h-21 z M8,31 h21 v 3 h-21 Z
    M10,5 h17 v16 h-17 z M9,6 h19 v14 h-19 Z
    M13,9 h1 v3 h-1 v-1 h3 v1 h-1 v-3 h1 v1 h-3 Z
    M21,9 h1 v3 h-1 v-1 h3 v1 h-1 v-3 h1 v1 h-3 Z
    M16,13 h1 v2 h2 v-2 h1 v1 h-4 Z
    M16,16 h5 v2 h3 v1 h-1 v-2 h-8 v 1 h 1 Z
    M9,26 h2 v1 h-2 Z
    M21,25 h6 v1 h-6 Z"></path>
</svg>
'
)

main "$@"


